[package]
name = "private-perps"
version = "0.1.0"
description = "PrivatePerps — Private Perpetual Trading on Solana via Arcium MPC"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "private_perps"
path = "src/lib.rs"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = "0.32.1"
arcium-macros = "0.1.0"
constant_time_eq = "0.3.0"



